receivers:
  otlp:
    protocols:
      grpc:
  prometheus/1:
    config:
      scrape_configs:
        - job_name: "forge_apps_metrics"
          scrape_interval: 15s
          static_configs:
            - targets: [ "host.docker.internal:9001" ]
              labels:
                instanceId: "instance-99"


exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
  logging:

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:
  seedingmetrics:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger]
    metrics:
      receivers: [prometheus/1]
      processors: [seedingmetrics,batch]
      exporters: [logging, prometheus]
